@startuml
skinparam style strictuml
header Sistema de Restaurant - Basat en D13
actor "Client" as C
boundary "Interfície Comanda" as UI
control "Gestor Comandes" as GC
entity "Comanda" as COM
actor "Cuiner" as K

title Sistema de Comandes Restaurant

== Selecció ==
C -> UI: seleccionarPlats(Llista)
activate UI
UI -> GC: validarPlats(Llista)
activate GC
GC --> UI: validado
deactivate GC
UI --> C: mostrar confirmació
deactivate UI


== Creació y Pagament ==
C -> UI: confirmarComanda()
activate UI
UI -> GC: generarComanda(plats)
activate GC
create COM
GC -> COM: new(plats)
GC --> UI: comanda creada
deactivate GC

C -> UI: pagar()
UI -> GC: processarPagament()
activate GC

alt si vol afegir propina
    C -> UI: introduirPropina(import)
    UI -> GC: aplicarPropina(id, import)
    GC -> COM: setPropina(import)
end

GC --> UI: pagament finalitzat
deactivate GC
UI --> C: lliurar tiquet
deactivate UI

== Notificació a Cuina ==
GC -> K: notificarNouPedido(id)





== Fase de Notificació a Cuina ==
@enduml